import { cn } from "@/app/lib/cn";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { Header } from "./common/Header";
import { Footer } from "./common/Footer";
import { Seo } from "./common/Seo";
import "./globals.css";

// Body Font
const inter = Inter({ subsets: ["latin"] });

// Heading Font
const manrope = localFont({
  src: [
    {
      path: "../public/fonts/Manrope-Bold.ttf",
    },
  ],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "RWB Solution International",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body
        className={cn(
          "bg-black",
          inter.className,
          manrope.variable,
          "antialiased"
        )}
      >
        <Header />
        <main>{children}</main>
        <Seo />
        <Footer />
      </body>
    </html>
  );
}
